export const DB_PROVIDE_NAME = 'DATA_SOURCE';
export const DB_VENUE_PROVIDER_REPOSITORY_NAME = 'VENUE_REPOSITORY';
export const DB_AVAILABILITY_PROVIDER_REPOSITORY_NAME =
  'AVAILABILITY_REPOSITORY';
export const DB_COURSE_PROVIDER_REPOSITORY_NAME = 'COURSE_REPOSITORY';
export const DB_USER_PROVIDER_REPOSITORY_NAME = 'USER_REPOSITORY';
export const DB_DEPARTMENT_PROVIDER_REPOSITORY_NAME = 'DEPARTMENT_REPOSITORY';
export const DB_FACULTY_PROVIDER_REPOSITORY_NAME = 'FACULTY_REPOSITORY';
export const DB_LEVEL_PROVIDER_REPOSITORY_NAME = 'LEVEL_REPOSITORY';
export const DB_TIME_PROVIDER_REPOSITORY_NAME = 'TIME_REPOSITORY';
export const DB_LECTURER_PROVIDER_REPOSITORY_NAME = 'LECTURER_REPOSITORY';
