export * from './availability.entity';
export * from './course.entity';
export * from './department.entity';
export * from './faculty.entity';
export * from './lecturer.entity';
export * from './level.entity';
export * from './time.entity';
export * from './user.entity';
export * from './venue.entity';
